annotationGenerators: # Generators we want to use, keep it as is for any API Platform project
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DunglasApiAnnotationGenerator
namespaces:
  entity: AppBundle\Entity # The default namespace for entities, following API Platform and Symfony best practices
types: # The list of type to generated (a PHP entity class by type will be generated)
  Article: # Schema.org has an inheritance system, we will configure all types of the hierarchy
    properties: # The list of properties we want to use
      articleBody: { range: "Text" }
      images:
        range: ImageObject # PHP Schema handle relations. Here we force the type of the property to Person
        cardinality: (*..*) # Force the cardinality of the relation
  CreativeWork:
    parent: false
    properties:
      headline: ~
      slug: { range: "Text" }
      published: { range: "Boolean" }
  ImageObject:
    parent: MediaObject
    properties:
      caption: ~
  MediaObject:
    properties:
      contentSize: ~
      contentUrl: ~
      height:  { range: "Integer" }
      width:  { range: "Integer" }